<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>2ffb6e1b-485f-4ba7-bcbb-8af9983a3801</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "More fish, fewer sharks" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
